name: Custom Death
version: '${project.version}'
main: dev.jannek.customdeath.CustomDeath
api-version: 1.19
authors: [ 'Jannek' ]
description: 'Custom death and revival system.'
website: 'http://jannek.dev'
